package tw.com.business_meet.vo;// default package
// Generated 2020/3/24 �U�� 07:27:15 by Hibernate Tools 5.2.12.Final




import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * UserInformation generated by hbm2java
 */
@Entity
@Table(name = "user_information", schema = "dbo", catalog = "business_meet")
public class UserInformation implements java.io.Serializable {

	private String blueTooth;
	private String userName;
	private String company;
	private String position;
	private String avatar;
	private String tel;
	private String email;
	private Date createDate;
	private Date modifyDate;
	private Set<Matched> matchedsForMatchedBlueTooth = new HashSet<Matched>(0);
	private Set<Matched> matchedsForBlueTooth = new HashSet<Matched>(0);

	public UserInformation() {
	}

	public UserInformation(String blueTooth, String userName, String company, String position, String avatar, String tel, String email, Date createDate, Date modifyDate) {
		this.blueTooth = blueTooth;
		this.userName = userName;
		this.company = company;
		this.position = position;
		this.avatar = avatar;
		this.tel = tel;
		this.email = email;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}


	public UserInformation(String blueTooth, String userName, String company, String position, String avatar, String tel, String email, Date createDate, Date modifyDate, Set<Matched> matchedsForMatchedBlueTooth, Set<Matched> matchedsForBlueTooth) {
		this.blueTooth = blueTooth;
		this.userName = userName;
		this.company = company;
		this.position = position;
		this.avatar = avatar;
		this.tel = tel;
		this.email = email;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.matchedsForMatchedBlueTooth = matchedsForMatchedBlueTooth;
		this.matchedsForBlueTooth = matchedsForBlueTooth;
	}

	@Id

	@Column(name = "blue_tooth", unique = true, nullable = false, length = 18)
	public String getBlueTooth() {
		return this.blueTooth;
	}

	public void setBlueTooth(String blueTooth) {
		this.blueTooth = blueTooth;
	}

	@Column(name = "user_name", nullable = false, columnDefinition = "nvarchar(100)")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "company", nullable = false, columnDefinition = "nvarchar(100)")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "position", columnDefinition = "nvarchar(100)")
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "avatar")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}




	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInformationByMatchedBlueTooth")
	public Set<Matched> getMatchedsForMatchedBlueTooth() {
		return this.matchedsForMatchedBlueTooth;
	}

	public void setMatchedsForMatchedBlueTooth(Set<Matched> matchedsForMatchedBlueTooth) {
		this.matchedsForMatchedBlueTooth = matchedsForMatchedBlueTooth;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userInformationByBlueTooth")
	public Set<Matched> getMatchedsForBlueTooth() {
		return this.matchedsForBlueTooth;
	}

	public void setMatchedsForBlueTooth(Set<Matched> matchedsForBlueTooth) {
		this.matchedsForBlueTooth = matchedsForBlueTooth;
	}

}
